version: "3.9"

services:
  api:
    build: ./api-service
    container_name: itconsultant-api
    ports:
      - "8081:8081"
    restart: unless-stopped

  web:
    build: ./web-service
    container_name: itconsultant-web
    ports:
      - "8080:8080"
    depends_on:
      - api
    restart: unless-stopped
