apiversion: apps/v1
kind: Deployment  
metadata:
  name: web-service 
  labels:
    app: web-service  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:   
      labels:
        app: web-service  
    spec:
      containers:
        - name: web-service
          image: web-service:latest
          ports:
            - containerPort: 8080
          restartPolicy: Always
  
  #service 
---
apiversion: v1
kind: Service
metadata:
  name: web-service  
spec:
  type: LoadBalancer
  selector:
    app: web-service  
  ports:
      -port: 8080
      targetPort: 8080 