resources:
  - ../../base

nameSuffix: -dev

patches:
  # API service overrides
  - target:
      kind: Deployment
      name: api-service
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-service
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: api-service
                image: gowobo/api-service:v1

  # WEB service overrides
  - target:
      kind: Deployment
      name: web-service
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-service
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: web-service
                image: gowobo/web-service:v1
